# Generated by Django 4.2.9 on 2024-01-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('question', models.TextField(max_length=400)),
                ('priority', models.CharField(choices=[{'High', 'H'}, {'Medium', 'M'}, {'Low', 'L'}], max_length=6)),
            ],
            options={
                'verbose_name': 'The Question',
                'verbose_name_plural': "People's Questions",
            },
        ),
    ]
